'use client'

import Image from "next/image";
import styles from './recigrab.module.css'
import {
  IoFastFood,
  IoList,
  IoNutrition,
  IoPlayCircle,
  IoTimer,
  IoSparkles
} from "react-icons/io5";
import projects from "@/data/projects";
import { useState } from "react";

const pages = [
  {
    index: 0,
    id: "home",
    page: "Home",
    title: "All your saved recipes in one place.",
    screenshotUrl: '/images/recigrab/screenshots/home-b.webp',
    features: [
      {
        title: "Import from Instagram",
        description: "Save recipes directly from social media with a single tap.",
        icon: IoSparkles
      },
      {
        title: "Search anything",
        description: "Search by ingredients, name, or meal type instantly.",
        icon: IoFastFood
      },
    ]
  },
  {
    index: 1,
    id: "recipe",
    page: "Recipe",
    title: "Clean, readable recipes generated by AI.",
    screenshotUrl: '/images/recigrab/screenshots/recipe-b.webp',
    features: [
      {
        title: "AI-generated ingredients & steps",
        description: "Messy captions are converted into structured recipes automatically.",
        icon: IoSparkles
      },
      {
        title: "Serving size scaling",
        description: "Adjust servings and ingredients update instantly.",
        icon: IoNutrition
      },
    ]
  },
  {
    index: 2,
    id: "cooking",
    page: "Cooking Mode",
    title: "Cook without touching your phone.",
    screenshotUrl: '/images/recigrab/screenshots/cooking-mode-b.webp',
    features: [
      {
        title: "Hands-free friendly",
        description: "Designed to minimize interaction while cooking.",
        icon: IoFastFood
      },
    ]
  },
]

export default function ReciGrab() {
  const [currentPage, setCurrentPage] = useState<number>(0);

  return (
    <div>
      <title>ReciGrab – BySaether</title>

      {/* Front / Hero */}
      <section className={styles.front}>
        <Image
          src={'/images/recigrab/frontpage.webp'}
          alt={''}
          width={1500}
          height={2000}
          quality={100}
          priority
        />

        <div className={styles.appDescription}>
          <div className={styles.logoContainer}>
            <Image
              src={'/images/recigrab/logo.svg'}
              alt={'ReciGrab logo'}
              width={200}
              height={200}
            />
            <span>ReciGrab</span>
          </div>

          <h1>Save recipes. Cook smarter.</h1>

          <p>
            ReciGrab turns social media recipes into clean, structured cooking instructions.
            Perfect for meal prep, busy weekdays, and anyone tired of scrolling while cooking.
          </p>

          <a href={projects.find(p => p.id === 'recigrab')!.appStore!.apple}>
            <Image
              src={'/images/appstore/apple-darkmode.svg'}
              alt={`Apple App Store Link`}
              width={150}
              height={50}
              style={{ objectFit: "contain", marginTop: "1em" }}
            />
          </a>

          <span id="intersector" />
        </div>
      </section>

      {/* Feature switcher */}
      <section className={styles.section}>
        <div className={styles.switchView}>
          <div className={styles.switchContainer}>
            {pages.map(page => (
              <button
                key={page.id}
                className={`${styles.switchButton} ${pages[currentPage].id === page.id ? styles.active : ''}`}
                onClick={() => setCurrentPage(pages.findIndex(p => p.id === page.id))}
              >
								<div>
                	<h3>{page.page}</h3>
								</div>
              </button>
            ))}
          </div>

          <div key={pages[currentPage].id} className={styles.switchViewDesc}>
            <p>{pages[currentPage].page}</p>
            <h2>{pages[currentPage].title}</h2>

            {pages[currentPage].features.map((feature, index) => (
              <div key={index} className={styles.feature}>
                <span>
                  <feature.icon />
                  {feature.title}
                </span>
                <p>{feature.description}</p>
              </div>
            ))}
          </div>

          <div className={styles.switchViewImages}>
            {pages.map((page, index) => {
              const prevIndex = (currentPage - 1 + pages.length) % pages.length;
              const nextIndex = (currentPage + 1) % pages.length;

              let positionClass = "";
              if (index === currentPage) positionClass = styles.middle;
              else if (index === prevIndex) positionClass = styles.left;
              else if (index === nextIndex) positionClass = styles.right;

              return (
                <Image
                  key={page.id}
                  src={page.screenshotUrl}
                  alt={'Screenshot of ReciGrab app'}
                  width={492}
                  height={1000}
                  quality={100}
                  className={positionClass}
                />
              )
            })}
          </div>
        </div>
      </section>
    </div>
  )
}
