'use client'

import ProductLandingPage, {type ProductView} from "@/components/ProductLandingPage";
import {IoFastFood, IoNutrition, IoSparkles} from "react-icons/io5";

const views: ProductView[] = [
  {
    id: "home",
    label: "Home",
    title: "All your saved recipes in one place.",
    screenshotUrl: "/images/recigrab/screenshots/home-b.webp",
    features: [
      {
        title: "Import from Instagram",
        description: "Save recipes directly from social media with a single tap.",
        icon: IoSparkles,
      },
      {
        title: "Search anything",
        description: "Search by ingredients, name, or meal type instantly.",
        icon: IoFastFood,
      },
    ],
  },
  {
    id: "recipe",
    label: "Recipe",
    title: "Clean, readable recipes generated by AI.",
    screenshotUrl: "/images/recigrab/screenshots/recipe-b.webp",
    features: [
      {
        title: "AI-generated ingredients & steps",
        description: "Messy captions are converted into structured recipes automatically.",
        icon: IoSparkles,
      },
      {
        title: "Serving size scaling",
        description: "Adjust servings and ingredients update instantly.",
        icon: IoNutrition,
      },
    ],
  },
  {
    id: "cooking",
    label: "Cooking Mode",
    title: "Cook without touching your phone.",
    screenshotUrl: "/images/recigrab/screenshots/cooking-mode-b.webp",
    features: [
      {
        title: "Hands-free friendly",
        description: "Designed to minimize interaction while cooking.",
        icon: IoFastFood,
      },
    ],
  },
];

export default function ReciGrab() {
  return (
    <ProductLandingPage
      projectId="recigrab"
      name="ReciGrab"
      pageTitle="ReciGrab - BySaether"
      headline="Save recipes. Cook smarter."
      description="ReciGrab turns social media recipes into clean, structured cooking instructions. Perfect for meal prep, busy weekdays, and anyone tired of scrolling while cooking."
      heroImage="/images/recigrab/frontpage.webp"
      logo="/images/recigrab/logo.svg"
      logoVariant="recigrab"
      views={views}
      legalLinks={[
        {href: "/recigrab/privacy-policy", label: "Privacy Policy"},
        {href: "/recigrab/terms-of-service", label: "Terms of Service"},
        {href: "/recigrab/manage-data", label: "Manage Data"},
      ]}
    />
  );
}
